services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload 